# Load Antigen
source ~/dotfiles/zsh/antigen/antigen.zsh

# Ensure editor is set
export EDITOR=vim
export TERM="xterm-256color"
#ntigen bundle jdavis/zsh-files
antigen use oh-my-zsh

## Antigen Theme
#antigen theme robbyrussell/oh-my-zsh themes/clean
#antigen theme jdavis/zsh-files themes/jdavis
antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train

# For SSH, starting ssh-agent is annoying
antigen bundle ssh-agent
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle rupa/z
#antigen bundle docker
antigen bundle archlinux
antigen bundle tmux
antigen bundle adb
antigen bundle systemd
antigen bundle voronkovich/gitignore.plugin.zsh
antigen-bundle Tarrasch/zsh-autoenv


#zsh promt
#export PROMPT='%{$fg[cyan]%}[%{$fg[white]%} %n@%m %{$fg[cyan]%}] [%{$fg[white]%}%~%{$fg[cyan]%}] >%{$reset_color%} '

antigen apply

#ssh-agent use dsa
zstyle :omz:plugins:ssh-agent identities id_dsa

BULLETTRAIN_PROMPT_ORDER=(
  time
  status
  custom
  context
  dir
  git
)

mini() { minicom -w -c on -D /dev/ttyUSB$1 -C /tmp/log_for_usb$1 }
source ~/dotfiles/zsh/zsh_alias
